.TH RGOL 1 "2016\-12\-30" "rgol 1.0.0" "User Commands"
.SH NAME
.PP
rgol \- Conway's game of life in Rust for terminals
.SH SYNOPSIS
.PP
\fB\fCrgol\fR \fB\fCgenmap\fR \fINROW\fP \fINCOL\fP [\fB\fC\-s\fR]
.br
\fB\fCrgol\fR \fB\fCplay\fR \fIFILE\fP [\fITICK_MS\fP]
.SH DESCRIPTION
.TP
\fB\fCgenmap\fR
Print an empty map.
.TP
\fB\fCplay\fR
Play the game.
.br
Ctrl + c exits cleanly
.SH OPTIONS
.TP
\fB\fC\-s\fR, \fB\fC\-\-space\fR
Add spaces to the map.
.br
Makes the map somewhat isotropic with monospaced fonts.
.SH MAPS
.PP
Maps must be rectangular.
.PP
Whitespace is ignored. ‘·’ (U+00B7 MIDDLE DOT) is a dead cell. Anything else is a living cell.
.SH AUTHOR
.PP
Letheed \[la]letheed@outlook.com\[ra]
.SH SOURCE
.PP
Repository \[la]https://github.com/letheed/rgol\[ra]
.br
Bug tracker \[la]https://github.com/letheed/rgol/issues\[ra]
.SH COPYRIGHT
.PP
Copyright © 2015 Letheed. License MIT.
